### PR TITLE
Fix serviceAccountName

### PR DESCRIPTION
**Pull request by ssz1997**
A followup to https://github.com/Alluxio/k8s-operator/pull/12. That PR changed the name of the serviceAccount but didn't update in the CSI configurations.

### CODE REVIEW

**Review by Kai-Zhang — APPROVED** [review]
LGTM

**Comment by Kai-Zhang** [comment]
btw, are the automated tests adequate for this problem? i mean with the existing automated tests we could have found this problem in #12, right?

**Comment by ssz1997** [comment]
Good question. This string is actually hard-coded everywhere so the test would not catch it, not to mention PR #12 doesn't have the test implemented yet. Let me make it non-hardcoded.

**Comment by ssz1997** [comment]
@Kai-Zhang PTAL. Thanks!

**Review by Kai-Zhang — APPROVED** [review]
LGTM

**Pull request merged**
